modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="citymod"
version="1.0.0"
displayName="CityMod"
displayURL=""
credits="Ааыыыыыыаааыыааыыы"
authors="-"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.citymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration